package dependencies

object DependencyVersions {
    const val kotlin_version = "1.9.0"
    const val core_version = "1.9.0"
    const val appcompat_version = "1.6.1"
    const val lifecycle_version = "2.6.1"
    const val coroutines_version = "1.7.3"
    const val compose_activity_version = "1.7.2"
    const val compose_version = "1.5.1"
    const val compose_compiler_version = "1.5.1"
    const val compose_material3_version = "1.1.1"
    const val constraintlayout_compose_version = "1.0.1"
    const val compose_tracing_version = "1.0.0-alpha03"
    const val junitTestImplementation_version = "4.13.2"
    const val junitExtAndroidTestImplementation_version = "1.1.5"
    const val espressoAndroidTestImplementation_version = "3.5.1"
    const val navigation_version = "2.6.0"
    const val hilt_version = "2.47"
    const val hilt_compose_version = "1.0.0"
    const val retrofit_version = "2.9.0"
    const val gson_version = "2.10.1"
    const val okhttp_version = "4.10.0"
    const val glide_version = "4.16.0"
    const val glide_transformations = "4.3.0"
    const val loggingInterceptor_version = "4.9.1"
    const val drawablePainter_version = "0.16.0"
    const val accompanistCoil_version = "0.13.0"
    const val splashScreen_version = "1.0.1"
    const val room_version = "2.5.2"
    const val firebase_auth_ktx = "22.1.2"
    const val firebase_database = "20.2.2"
}